on:
  workflow_call:
    inputs:
      # terraform
      TERRAFORM_VERSION:
        type: string
       # environment
      ENVIRONMENT:
        type: string
    secrets:
      TFSTATE_RESOURCE_GROUP_NAME:
        required: true
      TFSTATE_STORAGE_ACCOUNT_NAME:
        required: true
      TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY:
        required: true
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true
jobs:
  # apply stages
  apply_stage:
    name: apply terraform
    runs-on: ubuntu-latest
    steps:
      - name: "apply terraform"
        run: echo 'apply terraform'