on:
 workflow_call:
   inputs:
     terraform_version:
       required: true
       type: string
     terraform_directory:
       type: string
       default: src
   secrets:
     CLIENT_ID:
       required: true
     SUBSCRIPTION_ID:
       required: true
     TENANT_ID:
       required: true
jobs:
  terraform-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: 'Az login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Terraform ${{ inputs.terraform_version }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}
      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ inputs.terraform_directory }}
        continue-on-error: false
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ inputs.terraform_directory }}
      - name: Terraform Validation
        id: validate
        run: terraform validate
        working-directory: ${{ inputs.terraform_directory }}
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{ inputs.terraform_directory }}
  

        # uses: azure/powershell@v1
        # with:
        #  inlineScript: |
        #     Write-Host "Installing Terraform ${{ inputs.terraform_version }}"
        #     Write-Host "the secret ${{ secrets.a_token }}"
        #  azPSVersion: "latest"