on: [workflow_call]

jobs:
  # plan stages
  plan_dev:
    name: plan infradev dev terraform
    runs-on: ubuntu-latest
    steps:
      - name: "plan terraform dev"
        run: echo 'plan terraform'