on: [workflow_dispatch]

jobs:
  # plan infradev dev stage
  plan_infradev_dev:
    name: plan infradev dev terraform
    runs-on: ubuntu-latest
    steps:
      - name: "plan terraform"
        run: echo 'plan terraform'
  plan_infradev_uat:
    name: plan infradev uat terraform
    runs-on: ubuntu-latest
    steps:
      - name: "plan terraform"
        run: echo 'plan terraform'
  plan_infradev_prd:
    name: plan infradev prd terraform
    runs-on: ubuntu-latest
    steps:
      - name: "plan terraform"
        run: echo 'plan terraform'
  # deploy infradev dev/uat/prd
  apply_infradev_dev:
    name: apply infradev dev terraform
    environment: infradev_dev
    runs-on: ubuntu-latest
    needs: [plan_infradev_dev]
    steps:
      - name: "apply terraform"
        run: echo 'apply terraform'
  apply_infradev_uat:
    name: apply infradev uat terraform
    environment: infradev_uat
    runs-on: ubuntu-latest
    needs: [apply_infradev_dev, plan_infradev_uat]
    steps:
      - name: "apply terraform"
        run: echo 'apply terraform'
  apply_infradev_prod:
    name: apply infradev prd terraform
    environment: infradev_prod
    runs-on: ubuntu-latest
    needs: [apply_infradev_uat, plan_infradev_prd]
    steps:
      - name: "apply terraform"
        run: echo 'apply terraform'
