on:
 workflow_call:
   inputs:
     terraform_version:
       required: true
       type: string
   secrets:
      a_token:
       required: true
jobs:
  terraform-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Terraform ${{ inputs.terraform_version }}
        uses: azure/powershell@v1
        with:
         inlineScript: |
            Write-Host "Installing Terraform ${{ inputs.terraform_version }}"
            Write-Host "the secret ${{ secrets.a_token }}"
         azPSVersion: "latest"