on:
  workflow_call:
    inputs:
      # terraform
      TERRAFORM_VERSION:
        type: string
        # environment
      ENVIRONMENT:
        type: string
    secrets:
      TFSTATE_RESOURCE_GROUP_NAME:
        required: true
      TFSTATE_STORAGE_ACCOUNT_NAME:
        required: true
      TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY:
        required: true
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENANT_ID:
        required: true
jobs:
  apply:
    name: plan terraform
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    env:
      ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
    steps:
      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v3
        with:
          name: terraform_plan_${{ inputs.ENVIRONMENT }}
          path: ${{ github.workspace }}/resources
      - name: Upzip Terraform Artifacts
        run: |
          ls -R
          7z x -t7z ./terraform.7z ./terraform -p"{{ $secrets.TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY }}"
          ls -R
        working-directory: ${{ github.workspace }}/resources
      - name: Terraform Apply
        run: |
          ls
        working-directory: ${{ github.workspace }}/resources/terraform
