name: terraform Release
on: [workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  tf:
    uses: Fodsuk/github-workflow-play/.github/workflows/template-terraform-plan-stage.yml@init