name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    uses: Fodsuk/workflow-templates/.github/workflows/template-terraform-ci.yml@v1.0.18
    with:
      TERRAFORM_VERSION: 1.2.6
      ENVIRONMENT: ci
    secrets:
      HIERA_FACTS: ${{ secrets.ENVIRONMENT_HIERA_FACTS }}
      CLIENT_ID: ${{ secrets.ENVIRONMENT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ENVIRONMENT_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ENVIRONMENT_PRIMARY_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ENVIRONMENT_TENANT_ID }}