name: terraform Release
on: [workflow_dispatch, push]
permissions:
  id-token: write
  contents: read
jobs:
  all:
    uses: Fodsuk/github-workflow-play/.github/workflows/template-terraform-release.yml@init
    
