name: Terraform Pull Request
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  dev:
    uses: Fodsuk/workflow-templates/.github/workflows/template-terraform-pull_request-stage.yml@v1.0.17
    with:
      TERRAFORM_VERSION: 1.2.6
      ENVIRONMENT: management-group-roddas-plt-dev-grp-reader
    secrets:
      TFSTATE_RESOURCE_GROUP_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_RESOURCE_GROUP_NAME }}
      TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_NAME }}
      TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY }}
      HIERA_FACTS: ${{ secrets.ENVIRONMENT_HIERA_FACTS }}
      CLIENT_ID: ${{ secrets.ENVIRONMENT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ENVIRONMENT_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ENVIRONMENT_PRIMARY_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ENVIRONMENT_TENANT_ID }}
  uat:
    uses: Fodsuk/workflow-templates/.github/workflows/template-terraform-pull_request-stage.yml@v1.0.17
    with:
      TERRAFORM_VERSION: 1.2.6
      ENVIRONMENT: management-group-roddas-plt-uat-grp-reader
    secrets:
      TFSTATE_RESOURCE_GROUP_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_RESOURCE_GROUP_NAME }}
      TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_NAME }}
      TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY }}
      HIERA_FACTS: ${{ secrets.ENVIRONMENT_HIERA_FACTS }}
      CLIENT_ID: ${{ secrets.ENVIRONMENT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ENVIRONMENT_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ENVIRONMENT_PRIMARY_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ENVIRONMENT_TENANT_ID }}
  prod:
    uses: Fodsuk/workflow-templates/.github/workflows/template-terraform-pull_request-stage.yml@v1.0.17
    with:
      TERRAFORM_VERSION: 1.2.6
      ENVIRONMENT: management-group-roddas-plt-prd-grp-reader
    secrets:
      TFSTATE_RESOURCE_GROUP_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_RESOURCE_GROUP_NAME }}
      TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_NAME }}
      TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY: ${{ secrets.ENVIRONMENT_TFSTATE_STORAGE_ACCOUNT_ACCESS_KEY }}
      HIERA_FACTS: ${{ secrets.ENVIRONMENT_HIERA_FACTS }}
      CLIENT_ID: ${{ secrets.ENVIRONMENT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ENVIRONMENT_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.ENVIRONMENT_PRIMARY_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.ENVIRONMENT_TENANT_ID }}