name: terraform CI
on: [push]
jobs:
  terraform-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello from run command
        run: Write-Host "hello from run command"
      - name: powershell-hello-world
        uses: azure/powershell@v1
        with:
         inlineScript: |
            Write-Host "hello!"
         azPSVersion: "latest"