name: terraform CI
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  tf:
    uses: Fodsuk/github-workflow-play/.github/workflows/template-terraform-ci.yml@init
    with:
      terraform_version: 1.1.0
    secrets:
     CLIENT_ID: ${{ secrets.ACTION_CLIENT_ID }}
     SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
     TENANT_ID: ${{ secrets.TENANT_ID }}



# creating template
# on:
#   workflow_call:
#     inputs:
#       terraform_version:
#         required: true
#         type: string

# using inputs
#${{ inputs.terraform_version }}


# referencing the reusable
# on:
#   work_dispatch:
# jobs:
#  create_terraform:
    # use: mikerodda/reponame/.github/workflows/templatename.yml@main
    #  with:
    #    terraform_version: 1.2.1
      

