name: Continuous Integration
on: [workflow_dispatch, pull_request]
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    uses: Fodsuk/workflow-templates/.github/workflows/template-terraform-ci.yml@v0.0.1
    with:
      terraform_version: 1.2.6
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
